version: '2.3'

volumes:
  data-postgres:
    driver: "local"
  data-opennms-share:
    driver: "local"
  data-opennms-etc:
    driver: "local"
  data-elasticsearch:
    driver: "local"

services:
  database:
    image: postgres:10
    container_name: opennms-database
    env_file:
      - env/postgres.env
    environment:
      - TZ=Europe/Berlin
    ports:
      - "5432"
    volumes:
      - data-postgres:/var/lib/postgresql/data

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    ports:
      - "5601:5601"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    env_file:
      - env/elasticsearch.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  opennms:
    image: opennms/horizon-core-web:latest
    container_name: opennms
    cap_add:
      - NET_ADMIN
    env_file:
      - env/opennms.env
      - env/postgres.env
    environment:
      - TZ=Europe/Berlin
    depends_on:
      - database
    volumes:
      - data-opennms-etc:/opt/opennms/etc
      - data-opennms-share:/data-opennms-share
      - ./etc-overlay:/opt/opennms-etc-overlay
    command: ["-s"]
    ports:
      - "8980:8980"
      - "8101:8101"
      - "61616:61616"
      - "162:162/udp"

  minion-01:
    image: opennms/minion:latest
    container_name: minion-01
    env_file:
      - env/minion.env
    command: ["-f"]
    ports:
      - "8201:8201"
      - "50000:50000/udp"

  sentinel-01:
    image: opennms/sentinel:latest
    container_name: sentinel-01
    env_file:
      - env/sentinel.env
      - env/postgres.env
    environment:
      - SENTINEL_ID=sentinel-01
    volumes:
      - "./auto-deploy/features-jms.xml:/opt/sentinel/deploy/features-jms.xml"
    command: ["-f"]
    ports:
      - "8301:8301"

  sentinel-02:
    image: opennms/sentinel:latest
    container_name: sentinel-02
    env_file:
      - env/sentinel.env
      - env/postgres.env
    environment:
      - SENTINEL_ID=sentinel-02
    volumes:
      - "./auto-deploy/features-jms.xml:/opt/sentinel/deploy/features-jms.xml"
    command: ["-f"]
    ports:
      - "8302:8301"
